#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker01"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "e9faaeae715c4736bc2f86adb054f0a7" }
]

[assets]
directory = "./public"
